### ISSUE TITLE
Can Chemistry/Pipette sketchers be integrated with Semantic UI

### ISSUE THREAD

**Issue by cpudney** [saberinformatics/plp-semantic-ui#3]
G'day,

We've installed Semantic UI 0.64 with PP 2017r1, and it works well - thanks for creating it.

We've not been able to work out how to incorporate a sketcher into a Semantic UI form. 

Chemistry Sketcher is displayed as a small icon. Double-clicking it does launch the desktop drawing tool. Transferring a structure works too - the structure is displayed in place of the sketcher.

Pipette Sketcher is not displayed at all.

Thanks,
Chris.

**Comment by cpudney** [comment]
G'day,

Some investigation suggests that the issue lies in the relative URL rewriting that is done by the Semantic UI HTML Report Viewer.

Disabling the "relative URLs to absolute" PilotScript component allows the Chemistry Sketcher to be displayed (but might have other side effects).

It also resolves another issue when trying to display SVG chemical structures in Semantic UI pages.

Regards,
Chris.

**Comment by cpudney** [comment]
Appears to be fixed in v0.65 :+1:

**Comment by saberinfo** [comment]
Hi Chris,

Yes, please use v0.65 (latest release as of today).

There is a Biovia sketcher example protocol included with it. We have not tested the Pipette sketcher.

If you identify any problems please reopen the issue or create a new one.

**Comment by cpudney** [comment]
Thanks - can confirm that Pipette can be integrated too.
