### ISSUE TITLE
jQuery/license.txt.txt needs to be renamed

### ISSUE THREAD

**Issue by cpudney** [saberinformatics/plp-semantic-ui#4]
G'day,

After installing v0.65 of the package I received the warning about restarting the server each time I attempted to display an HTML report created using Semantic UI components.

The warning script checks for the existence of .../jquery/license.txt but the file is named .../jquery/license.txt.txt in the package. Renaming it resolves the issue.

See https://github.com/saberinformatics/plp-semantic-ui/blob/master/saber/semantic/dataroot/data/assets/jquery/license.txt.txt

Regards,
Chris.

**Comment by saberinfo** [comment]
Chris, thank you! The file has been renamed in release v.0.65.1.

This may have affected some users but did not appear in my test environment after a fresh install.
