### ISSUE TITLE
List Box can't use Text from globals

### ISSUE THREAD

**Issue by arjd** [saberinformatics/plp-semantic-ui#5]
List Box tries to find "@global_property" on the data record rather than finding the global property named global_property.

`line 4, The expression was trying to access the value of a data record property '@global_property' but it is undefined or could not be calculated. One solution is to edit the PilotScript to test whether the property is defined before using it. This is done with the expression: %'@global_property' IS DEFINED.`

This is the problem:
```
if @Value is defined and @Value ne '' then
	@_s .= '<div class="item" data-value="'.property(@Value).'">'.property(@Text).'</div>'."\n";
else
	@_s .= '<div class="item" data-value="'.property(@Text).'">'.property(@Text).'</div>'."\n";
end if;
```

I would suggest:

```
if @Value is defined and @Value ne '' then
	@_s .= '<div class="item" data-value="'.eval(@Value).'">'.eval(@Text).'</div>'."\n";
else
	@_s .= '<div class="item" data-value="'.eval(@Text).'">'.eval(@Text).'</div>'."\n";
end if;
```

**Comment by arjd** [comment]
Previous suggestion didn't account for arrays... This might work better?

```
if @Value is defined and @Value ne '' then
	#value := eval(@Value);
	foreach #val in eval(@Text) loop
		@_s .= '<div class="item" data-value="'.#value.'">'.#val.'</div>'."\n";
	end loop;
else
	foreach #val in eval(@Text) loop
		@_s .= '<div class="item" data-value="'.#val.'">'.#val.'</div>'."\n";
	end loop;
end if;
```

**Comment by saberinfo** [comment]
Thank you for looking into this! Listbox can now use globals.
